name: CI

on:
  [ push ]

jobs:
  ci:
    environment: ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm run test

    - name: Publish release to npm
      uses: JS-DevTools/npm-publish@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.NPM_PUBLISH_TOKEN }}

    - name: Create Release draft
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: softprops/action-gh-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        prerelease: false

    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,ref,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
